name: Check compatibility

on:
  workflow_dispatch:
    inputs:
      downloadlink:
        description: 'APPX download link'
        required: true
        type: string
      gameversion:
        description: 'Game version'
        required: true
        type: string
        default: 'v1.'

jobs:
  check-compatibility:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check compatibility
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin
          mkdir tmp
          git worktree add tmp gh-pages

          curl -L "${{ github.event.inputs.downloadlink }}" -o mcappx.zip

          cmd /c CheckCompatibility.bat "${{ github.event.inputs.gameversion }}"
          
          git add tmp\compatibility-status.json
          git commit -m "Compatibility check"
          git push origin gh-pages